apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-sa-password
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mssql
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  password: {{ required "mssql.auth.saPassword is required" .Values.auth.saPassword | quote }}
