apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: mssql
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: mssql
      port: {{ .Values.service.port }}
      targetPort: mssql
      protocol: TCP
  selector:
    app.kubernetes.io/name: mssql
    app.kubernetes.io/instance: {{ .Release.Name }}
