apiVersion: v1
kind: Service
metadata:
  name: {{ include "apicurio-registry.uiFullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: apicurio-registry-ui
    app.kubernetes.io/component: ui
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
  selector:
    app.kubernetes.io/name: apicurio-registry-ui
    app.kubernetes.io/component: ui
    app.kubernetes.io/instance: {{ .Release.Name }}