replicaCount: 1

image:
  repository: mendhak/http-https-echo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

container:
  port: 8080

podAnnotations: {}

podLabels: {}

nodeSelector: {}

tolerations: []

affinity: {}