nav:
  - index.md
  - Deploy to k3s: k3s.md
  - Deploy to a remote cluster: remote-cluster.md
  - Deploy on AWS: aws.md
  - Seeding demo data: seeding-data.md
  - Scenarios: scenarios.md
  - Single sign-on: sso.md
  - ...
