apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-app
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: keycloak-db
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: kubernetes.io/basic-auth
stringData:
  username: {{ .Values.username | quote }}
  password: {{ .Values.password | quote }}
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-db
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: keycloak-db
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  instances: {{ .Values.instances }}
  imageName: {{ .Values.imageName }}

  bootstrap:
    initdb:
      database: {{ .Values.database }}
      owner: {{ .Values.username }}
      secret:
        name: keycloak-db-app

  storage:
    size: {{ .Values.storage.size }}
    storageClass: {{ .Values.storage.storageClass | default "local-path" }}

  monitoring:
    enablePodMonitor: false
